version: "3.9"
services:
  backend:
    build: "./backend"
    container_name: auth-app-be
    platform: "linux/amd64"
    ports:
      - "8000:8000"

  frontend:
    depends_on:
      - backend
    build: "./frontend"
    container_name: auth-app-fe
    platform: "linux/amd64"
    ports:
      - "3000:3000"
